name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    env:
      BACKEND_PORT: 5000
      BASE_URL: http://127.0.0.1:5000
      FRONTEND_PORT: 8000
      FRONTEND_URL: http://127.0.0.1:8000

    steps:
      # ------------------------------
      # Checkout code
      # ------------------------------
      - uses: actions/checkout@v4

      # ------------------------------
      # Setup Python
      # ------------------------------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock pylint python-dotenv

      # ------------------------------
      # Run Python linter
      # ------------------------------
      - name: Run Pylint
        working-directory: backend
        run: |
          pylint $(git ls-files '*.py') || true

      # ------------------------------
      # Run unit tests
      # ------------------------------
      - name: Run unit tests
        working-directory: backend
        run: pytest ../tests/unit

      # ------------------------------
      # Start Flask backend
      # ------------------------------
      - name: Start backend server
        working-directory: backend
        run: |
          nohup python app.py > /tmp/backend.log 2>&1 &
          echo $! > /tmp/backend.pid

      - name: Wait for backend
        run: |
          echo "Waiting for backend on port ${BACKEND_PORT}"
          for i in {1..60}; do
            curl -fsS "${BASE_URL}" && exit 0
            sleep 1
          done
          echo "Backend failed to start!"
          exit 1

      # ------------------------------
      # Node.js for ESLint + Newman + E2E tests
      # ------------------------------
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ------------------------------
      # Run ESLint on UI files
      # ------------------------------
      - name: Install frontend tools
        working-directory: UI
        run: |
          npm init -y
          npm install eslint --save-dev
          npx eslint --init  # optional

      - name: Run ESLint
        working-directory: UI
        run: |
          npx eslint "**/*.js" || true

      # ------------------------------
      # Run Postman tests (Newman)
      # ------------------------------
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: tests/integration/postman
        run: |
          newman run GSM.postman_collection.json \
            --env-var BASE_URL="${BASE_URL}"

      # ------------------------------
      # Static frontend server for E2E tests
      # ------------------------------
      - name: Install http-server
        run: npm install -g http-server

      - name: Start frontend server
        working-directory: UI
        run: |
          nohup http-server -p 5500 > /tmp/frontend.log 2>&1 &
          echo $! > /tmp/frontend.pid

      - name: Wait for frontend
        run: |
          echo "Waiting for frontend..."
          for i in {1..60}; do
            curl -fsS "${FRONTEND_URL}/index.html" && exit 0
            sleep 1
          done
          echo "Frontend failed to start!"
          exit 1

      # ------------------------------
      # Playwright E2E tests
      # ------------------------------
      - name: Install Playwright dependencies
        run: |
          pip install pytest-playwright
          playwright install

      - name: Run E2E tests
        run: pytest tests/e2e

      # ------------------------------
      # Debug logs if something breaks
      # ------------------------------
      - name: Dump logs on failure
        if: failure()
        run: |
          echo "=== BACKEND LOG ==="
          sed -n '1,200p' /tmp/backend.log || true

          echo "=== FRONTEND LOG ==="
          sed -n '1,200p' /tmp/frontend.log || true
